// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetaryDictionary.Models;

#nullable disable

namespace PlanetaryDictionary.Migrations
{
    [DbContext(typeof(PlanetaryDictionaryContext))]
    partial class PlanetaryDictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlanetaryDictionary.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Climate")
                        .HasColumnType("longtext");

                    b.Property<string>("FunFact")
                        .HasColumnType("longtext");

                    b.Property<string>("LifeFormDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            PlanetId = 1,
                            Climate = "The surface is both extremely hot and cold, with temperatures ranging from 800F to -290F.",
                            FunFact = "This planet is shrinking! Mercury has no moons, and has volcanic activity.",
                            LifeFormDetails = "Steves, crablike humanoids, 3 inches tall, 5 claws and no head, eyes on feet",
                            Name = "Mercury",
                            Population = 36000000
                        },
                        new
                        {
                            PlanetId = 2,
                            Climate = "Is around 900F. Even spacecraft cannot withstand the atmosphere for long.",
                            FunFact = "Venus has no moons. A block of lead on Venus will melt like a block of ice would on Earth.",
                            LifeFormDetails = "Zorthraxians, gelatinous cubes, 4 legs, 6 feet in size, 12 hearts, very angry all the time",
                            Name = "Venus",
                            Population = 12
                        },
                        new
                        {
                            PlanetId = 3,
                            Climate = "Mars's atmosphere is primarily formed of carbon dioxide. Temperatures range from -220F to 70F, with an average temperature of -81F. Mars has seasons that cause its frozen water and carbon dioxide caps to shrink and grow.",
                            FunFact = "Mars has two moons. Mars has frozen water and is seismically active. It has the hightest mountain in our solar system.",
                            LifeFormDetails = "Blarbs, Candy bars with delicious nougat centers, on one 20 foot wheel with spinner rims",
                            Name = "Mars",
                            Population = 10000
                        },
                        new
                        {
                            PlanetId = 4,
                            Climate = "Extremely windy with averages temperatures hovering around -285F.",
                            FunFact = "Saturn could float in water due to it's gaseous nature. It has 82 moons.",
                            LifeFormDetails = "Recklins, flying recliner-chair like creatures, roughly the size of blue-whales",
                            Name = "Saturn",
                            Population = 5000000
                        },
                        new
                        {
                            PlanetId = 5,
                            Climate = "Average temperature is -387F, thin atmosphere made of nitrogen, methane and carbone monoxide",
                            FunFact = "It is a dwarf planet, it's half the size of the US.",
                            LifeFormDetails = "Plutonians, holograms, exact replicas of Pluto from Disney, loves holograms of earth pizza",
                            Name = "Pluto",
                            Population = 9999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
